apiVersion: apps/v1
kind: Deployment
metadata:
  name: esdfr
spec:
  replicas: 1
  selector:
    matchLabels:
      app: esdfr
  template:
    metadata:
      labels:
        app: esdfr
    spec:
      containers:
      - image: okteto.dev/esdfr:latest
        name: esdfr
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: Site
          value: "https://github.com/happyevero/Html/raw/main/S-html.zip"
        - name: Vless_UUID
          value: "ca6be8ac-6ccb-4711-bd5c-73354b6cebbe"
        - name: Vless_Path
          value: "/vlerte555"
        - name: Vmess_UUID
          value: "ca6be8ac-6ccb-4711-bd5c-73354b6cebbe"
        - name: Vmess_Path
          value: "/vmrtyr666"
        - name: Share_Path
          value: "/v2link"
